export const SEARCH_NEWS_START = 'SEARCH_NEWS_START'
export const SEARCH_NEWS_REFRESH = 'SEARCH_NEWS_REFRESH'
export const SEARCH_NEWS_FAILED = 'SEARCH_NEWS_FAILED'
export const SEARCH_NEWS_SUCESS = 'SEARCH_NEWS_SUCESS'

export const SEARCH_MORE_NEWS_START = 'SEARCH_MORE_NEWS_START'
export const SEARCH_MORE_NEWS_FAILED = 'SEARCH_MORE_NEWS_FAILED'
export const SEARCH_MORE_NEWS_SUCESS = 'SEARCH_MORE_NEWS_SUCESS'

export const CHANGE_APP_THEME = 'CHANGE_APP_THEME'